### ISSUE TITLE
Validate that all structure formats and method signatures work with PagerDuty API

### ISSUE THREAD

**Issue by theckman** [PagerDuty/go-pagerduty#389]
We're making `v1.5.0` a special release, where we introduce breaking changes to fix issues within this package that probably never worked since being merged. Since we've fixed so many things so far, we should go over the entire package to make sure there are no outstanding issues.

Files to check:

- [x] ability.go
- [x] addon.go (#405)
- [x] analytics.go
- [x] business_service.go (#405)
- [x] change_events.go (#396)
- [x] escalation_policy.go (#396) (#405)
- [x] event.go
- [x] event_v2.go
- [x] extension.go (#414) (#405)
- [x] extension_schema.go (#405)
- [x] incident.go (#405) (#414) 
- [x] log_entry.go (#405) (#414)
- [x] maintenance_window.go (#405) (#414)
- [x] notification.go (#405) (#414)
- [x] on_call.go (#405)
- [x] priorites.go (#405)
- [x] ruleset.go (#414)
- [x] schedule.go (#405) (#414)
- [x] service.go (#405) (#414)
- [x] service_dependency.go
- [x] service_integration.go
- [x] tag.go (#405)
- [x] team.go (#405) (#414)
- [x] user.go (#405) (#414)
- [x] vendor.go (#405)
- [x] webhook.go

**Comment by theckman** [comment]
Accomplished via #396, #405, and #414.
